### ISSUE TITLE
Window stack redesign

### ISSUE THREAD

**Issue by athairus** [team-phoenix/Phoenix#101]
In order to better fit our design goals, some tweaks have to be done to certain parts of the UI in order to allow the user to browse the library with a game paused in the background.

Only problem I see in implementing this is the transition from closing the running game from the library. Will the library's navigation state be impacted? It should be imperceptible to the user.

Here's a sketch of the new design:

![window stack](https://cloud.githubusercontent.com/assets/1216337/7017013/b9ffeb10-dcbe-11e4-9f2c-71a7cc0d70c8.PNG)

**Comment by Druage** [comment]
This was the idea I had also.

**Comment by athairus** [comment]
This behavior is EXACTLY what the 3DS does with its OS.

**Comment by Druage** [comment]
Only thing you'd need to do, is make it so the gamestack doesn't pop the game view off the stack when the home button is pressed. This is the current behavior.

**Comment by athairus** [comment]
Currently, we have GameView and MouseDrivenView for gameplay and browsing respectively. 

We should have GameView be the initial item on the stack, followed by MouseDrivenView on top. This way, we can easily pop the library view (critical: we need to preserve navigation state) and push it back in when the user wants to change a game. Hopefully it'll load quickly enough on slow systems that it won't be frustrating to the user.

**Comment by athairus** [comment]
StackView is now the way I want it.

#137 down!

**Comment by athairus** [comment]
This feature has been implemented for a while now.
