### ISSUE TITLE
Run Core on its own thread

### ISSUE THREAD

**Issue by athairus** [team-phoenix/Phoenix#107]
The UI and emulation should not block each other.

**Comment by athairus** [comment]
It would be better if we had Core run more or less autonomously with its own timer independent on the framerate of the emulated system or the host. At least it would prevent a slow core from blocking the UI thread...

Core:
- Could we perhaps have a mechanism for knowing when the core is not responding? I think we could do it by sending a signal to the Core with what time it is. Have this watchdog poll the Core with a repeating qTimer and if it the last signal it sends back is longer than n seconds ago, assume the Core is hung somehow...

Audio:
- Core may write data to AudioBuffer either sample by sample or by chunk, depending on the core. So, we may have to use mutexes to obtain access to the audioBuffer to write audio data, and Audio will have to do the same.

Video:
- Same deal, Core and VideoItem will have to share a buffer that holds a current video frame. I wonder if we'd get a tearing effect if we didn't use mutexes? Would anything crash?

Input:
- I think we'd have to poll input at 120Hz, if I understand the Nyquist sampling theorem right. And again, mutexes between Core and whatever handles input.

**Comment by Druage** [comment]
Hmm. This would work with signals and slots. The core would have to be subclassing a qobject though, but that's not much of a change. I like the idea. Checkout what gu1 did in the framelimiter in the VideoItem class. You could use that as a starting point for figuring out how to sync the core and the video item. I'd probably just use signals and slots though.

**Comment by Druage** [comment]
Also for the input, the core is what polls for controller for input, we just respond to event systems.

**Comment by athairus** [comment]
Looks like I forgot what kind of granularity a timer like QTimer gives. At best, we have 1ms resolution, which is hardly good enough for, say 60Hz vs 60.09Hz. Looks like I need to depend on Vsync after all

**Comment by athairus** [comment]
This seems like it'd a ton of work, but everything should be moved to its own thread that ISN'T related directly to the UI. Blocking operations like file I/O, network stuff, and audio and video processing are a start.

**Comment by Druage** [comment]
Most everything already is in its own thread. We use QtConcurrent for file io and metadata imports

**Comment by athairus** [comment]
So the deal with QTimer is that it's guaranteed to not fire *faster* than its given interval. On Windows by default the timer is done in 10ms increments, so we're probably only getting a frame drawn every 20ms. It's possible to increase the resolution on Windows:

http://www.qtcentre.org/threads/40317-frame-rate-and-QTimer-accuracy?p=185186#post185186
https://msdn.microsoft.com/en-us/library/windows/desktop/ms644900(v=vs.85).aspx#high_resolution

How does OS X and Linux handle this? How does Qt handle this on those platforms?

**Comment by athairus** [comment]
Do'h...
We never did this.

http://doc.qt.io/qt-5/qt.html#TimerType-enum

**Comment by athairus** [comment]
A note on the threaded renderer:

http://doc.qt.io/qt-5/qtquick-visualcanvas-scenegraph.html

The threaded renderer is currently used by default on Windows with opengl32.dll, Linux with non-Mesa based drivers, OS X, mobile platforms, and Embedded Linux with EGLFS but this is subject to change. It is possible to force use of the threaded renderer by setting QSG_RENDER_LOOP=threaded in the environment.

**Comment by athairus** [comment]
Currently, Core lives on its own thread just as I wanted it to. Buffer pools read and written to by Core and its consumer work just fine.

**Comment by athairus** [comment]
Before closing, confirm that the note on the QML scene graph render loop isn't relevant anymore.

**Comment by athairus** [comment]
Now Core is only on its "own" (separate from the qml thread) thread when in STATEREADY. This issue should continue in #162 and not here.
