### ISSUE TITLE
OS X: Suspends when in a different space

### ISSUE THREAD

**Issue by athairus** [team-phoenix/Phoenix#113]
To reproduce: 
- Have a fullscreen program running
- Run Phoenix on the desktop, run a game
- Move to the fullscreen app
- The audio from the game stops; Phoenix is suspended!

**Comment by athairus** [comment]
The reason for this is as we're currently invoking Core from the main thread, which is only repainting itself when the window manager asks it to, Core executing at all depends entirely on the window being visible.

The fix is to move Core to a different thread.

**Comment by athairus** [comment]
That's not the fix. If the windowing system is asking for a repaint, and Core only renders a frame when its container (VideoItem) is asked for a repaint, then Core won't update unless the windowing system continuously calls for repaints (is this totally right?)

Anyway, fix is to have a different timing source than window repaints.

**Comment by Druage** [comment]
VideoItem doesn't ask for a repaint, it's the QQuickWindow that is asking for a repaint from the windowing system. But ya the core won't continuously update. It's a feature of the WM.

**Comment by athairus** [comment]
But I didn't say that :)

**Comment by athairus** [comment]
Continued in #283
