### ISSUE TITLE
Pass text input to the searchbox and give it focus when in the GridView

### ISSUE THREAD

**Issue by DerianAndre** [team-phoenix/Phoenix#123]
When a rom is selected (highlighted) you can directly start typing in the keyboard and it will search like Zune

**Comment by athairus** [comment]
Behavior like what you're talking about isn't common at all in my experience, I can only think of a handful of places (besides Zune) where I can even do that. I really believe that removing the search box will confuse users, they will believe they can't search at all and complain.

**Comment by DerianAndre** [comment]
Yup my bad it should be no need to click the searchbox
