### ISSUE TITLE
Phoenix does not run with Qt4 and Qt5 installed on the same machine

### ISSUE THREAD

**Issue by Kaan88** [team-phoenix/Phoenix#131]
I'm on archlinux and even though the build successfully finishes the program doesn't start. I have qt5 installed and tried to build with both qtcreator and qmake, same result. 

This is the output.

[D] [phoenix.library]: Opening library database /home/kaan/.local/share/gamelibrary.sqlite
[F] QWidget: Cannot create a QWidget without QApplication

**Comment by athairus** [comment]
Are you sure you've gotten all the Qt libraries from the package manager? Or were you using the online installer? If it's the former, in my experience a lot of distros lag behind the current Qt releases.

**Comment by Kaan88** [comment]
I did select every single package, in fact I just chose the qt5 group which installed everything. Maybe archlinux doesn't ship with every package of qt5. Any way to know what is missing with cmake? It doesn't output anything.

**Comment by athairus** [comment]
Not entirely sure, the directions I wrote recommended the online installer. Can you confirm that you've downloaded at least Qt 5.4.1?

**Comment by Kaan88** [comment]
It is 5.4.2, these are the packages arch provides.
```
              qt5-base-5.4.2-1  qt5-connectivity-5.4.2-1
              qt5-declarative-5.4.2-1  qt5-enginio-5.4.2-1
              qt5-graphicaleffects-5.4.2-1  qt5-imageformats-5.4.2-1
              qt5-location-5.4.2-1  qt5-multimedia-5.4.2-1  qt5-quick1-5.4.2-1
              qt5-quickcontrols-5.4.2-1  qt5-script-5.4.2-1
              qt5-sensors-5.4.2-1  qt5-serialport-5.4.2-1  qt5-svg-5.4.2-1
              qt5-tools-5.4.2-1  qt5-translations-5.4.2-1  qt5-wayland-5.4.2-1
              qt5-webchannel-5.4.2-1  qt5-webengine-5.4.2-1  qt5-webkit-5.4.2-1
              qt5-websockets-5.4.2-1  qt5-x11extras-5.4.2-1
              qt5-xmlpatterns-5.4.2-1
```
I may try the online installer, but it really isn't preferable.

**Comment by athairus** [comment]
Okay. How are you launching it? I'm guessing either Qt Creator or, if the terminal, the Qt binaries are already in your path.

**Comment by Kaan88** [comment]
with ./phoenix

**Comment by athairus** [comment]
It's possible that Phoenix isn't reading the system QML files. You said you got the same output from Qt Creator?

**Comment by Kaan88** [comment]
Yeah same output, there are some issuies after building. No idea what they are.

![snapshot2](https://cloud.githubusercontent.com/assets/1260152/8110212/b95b21b0-1063-11e5-8026-18140befb36b.png)
I don't know how to check for qml files. But I can build and run other qt5 programs like smplayer and antimicro.

**Comment by athairus** [comment]
Quick question: do you have Qt 4 installed on your system? I know from experience that WILL cause conflicts.

**Comment by athairus** [comment]
In the meantime, I'm setting up an Arch VM to see what's going on.

**Comment by Druage** [comment]
That error normally comes up in the main.cpp file, because a QWidget is being created before the application loop as started. See https://github.com/team-phoenix/Phoenix/blob/master/src/main.cpp#L74.

This may be the issue and will be looked at soon.

**Comment by Kaan88** [comment]
Yeah, I actually do. Many programs need it so I can't remove it for testing. I'm checking the wiki now https://wiki.archlinux.org/index.php/Qt#QML , this qml command works.

**Comment by athairus** [comment]
I'm betting that's the issue.

**Comment by athairus** [comment]
If you find a solution to this (hey, maybe we configured our project wrong), let us know. We'll deal with this at some later point in the future, otherwise.

**Comment by Kaan88** [comment]
I've tried everything I could, and since it's not a missing dependency this
is out of my scope. I'm not a programmer, but I'll keep an eye on and will
test it.

On Thu, Jun 11, 2015 at 6:45 PM, athairus <notifications@github.com> wrote:

> If you find a solution to this (hey, maybe we configured our project
> wrong), let us know. We'll deal with this at some later point in the
> future, otherwise.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/team-phoenix/Phoenix/issues/131#issuecomment-111178235>
> .
>



-- 
Kaan Kasım

**Comment by Kaan88** [comment]
Removed qt4 temporarily and rebuilt. The result is the same.

**Comment by JosephMillsAtWork** [comment]
what is your toolkit and qmake set to ?

**Comment by Limero** [comment]
I have both Qt4 and 5 installed on Arch Linux and I'm able to compile and run without problems. 
Make sure you have the following installed: sdl2, qt5-base, qt5-multimedia, qt5-graphicaleffects, qt5-quickcontrols and qt5-svg. I'm compiling from terminal, follow the instructions on the Wiki.

**Comment by Kaan88** [comment]
Yeah, it worked fine after that complete rewrite.
