### ISSUE TITLE
Phoenix-Frontend PAL roms

### ISSUE THREAD

**Issue by flubbacrud** [team-phoenix/Phoenix#132]
Frontend currently runs PAL roms too fast. @Druage believes it is because of hard syncing to vsync

**Comment by athairus** [comment]
This issue depends on #220. I think we should use this heuristic: if the delta between vsync rate and the core's FPS is > 1, always use `Looper`.

**Comment by athairus** [comment]
This fix is implemented in `feature-backend` and this issue will be closed once that's committed to `master`

I went with a 2% heuristic by the way!
