### ISSUE TITLE
Pause button should steal double-click events

### ISSUE THREAD

**Issue by athairus** [team-phoenix/Phoenix#147]
Try double-clicking the pause button. What should happen is it should rapidly pause then resume. Instead, it pauses (or resumes) and the large MouseArea below it takes the double-click event and toggles the blur.

I tried taking a stab at the problem and couldn't figure out a good solution.

**Comment by Druage** [comment]
I noticed this too. An easy fix would be to add a blur toggle to an "effects" button on the ActionBar.

**Comment by athairus** [comment]
We removed the blur MouseArea, this bug's no longer relevant... for now.
