### ISSUE TITLE
"Make install" puts files all over the place 

### ISSUE THREAD

**Issue by Limero** [team-phoenix/Phoenix#149]
Currently, when you run "Make install", files are installed in non-standard places.
Description for where where files should be:
https://wiki.archlinux.org/index.php/Arch_packaging_standards#Directories
Tree of installed items:
```
├── home
│   └── Username
│       └── Documents
│           └── Phoenix
│               └── src
│                   └── Phoenix
│                       └── frontend
│                           └── release
│                               └── openvgdb.sqlite
├── include
│   └── quazip
│       ├── crypt.h
│       ├── ioapi.h
│       ├── JlCompress.h
│       ├── quaadler32.h
│       ├── quachecksum32.h
│       ├── quacrc32.h
│       ├── quagzipfile.h
│       ├── quaziodevice.h
│       ├── quazipdir.h
│       ├── quazipfile.h
│       ├── quazipfileinfo.h
│       ├── quazip_global.h
│       ├── quazip.h
│       ├── quazipnewinfo.h
│       ├── unzip.h
│       └── zip.h
├── lib
│   └── libquazip.a
├── opt
│   └── phoenix-backend
│       └── bin
│           └── libphoenix-backend.a
└── Phoenix
    └── bin
        └── Phoenix
```

**Comment by athairus** [comment]
`include` and `lib` are fixed. The quazip subrepo was set up to install library and header files when calling `make install`.

Not exactly sure how I can do the same for the backend. 

Basically, we're using `make install` for the whole project, which in the case of the subrepos means library and header files are installed to the "root", but in the case of frontend means the executable and its dependencies.

**Comment by athairus** [comment]
Continued in #172.
