### ISSUE TITLE
Make quazip external for Windows, dependency for OS X, Linux

### ISSUE THREAD

**Issue by Limero** [team-phoenix/Phoenix#150]
Make quazip external for Windows, and a dependency for OS X and Linux.
Homebrew (OS X), package name: quazip

Link to package and locations on Arch:
https://www.archlinux.org/packages/extra/x86_64/quazip-qt5/files/

Fedora:
https://apps.fedoraproject.org/packages/quazip-qt5/contents

Package on Ubuntu (probably is this one) and what it installs:
https://launchpad.net/ubuntu/utopic/+package/libquazip-qt5-dev
/usr
/usr/lib
/usr/lib/x86_64-linux-gnu
/usr/lib/x86_64-linux-gnu/libquazip-qt5.a
/usr/share
/usr/share/doc
/usr/share/doc/libquazip-qt5-dev
/usr/share/doc/libquazip-qt5-dev/copyright
/usr/lib/x86_64-linux-gnu/libquazip-qt5.so
/usr/share/doc/libquazip-qt5-dev/changelog.Debian.gz

**Comment by athairus** [comment]
So we have libquazip5 on Arch and Fedora, and libquazip-qt5 on Ubuntu. Guess we gotta do some checking for the library's existence before we add either to the list of linker libraries.

Since this is common to both frontend and backend, why not put it in the main .pro file, phoenix.pro?

**Comment by athairus** [comment]
We may be rolling our own custom code within quazip in the future, making depending on the system package not an option. Probably have to modify PATH on startup to ensure our custom version gets loaded.
