### ISSUE TITLE
GameView should be more resizable

### ISSUE THREAD

**Issue by DerianAndre** [team-phoenix/Phoenix#163]
So the problem here is when you are running a Rom and you want to resize the screen you can't because is it is restricted to the minimun height and width, maybe an option to have it in an other window can solve the problem, still we need that option.

**Comment by athairus** [comment]
I think we fixed this, confirm and close please!

**Comment by underr** [comment]
I'm having problems when resizing. Like this:

![sonic](https://u.pomf.io/mgoiac.png)

There should be 4 games here, but one is in the edge. Phoenix just show all them when I'm using a "correct" size of the window.

**Comment by athairus** [comment]
Hi, can you provide more detail as to how you got it to look like this?

Did you launch Phoenix and go to "Sega - Genesis", *or* did you play a game first and then went to "Sega - Genesis"?

**Comment by underr** [comment]
I got to "Sega - Genesis", added the games and played one of them a bit. Them I went back to the "Sega - Genesis" section.

**Comment by athairus** [comment]
No idea if this applies anymore. Feel free to open a new issue if it still does @underr.
