### ISSUE TITLE
Importing games "could" assign incorrect system name.

### ISSUE THREAD

**Issue by Druage** [team-phoenix/Phoenix#183]
Now the trick with this issue, is that if GameFileInfo::prepareMetadata() is run, and if GameFileInfo::system() is empty, the system name found from this function is appended to the game.

The issue with this is that GameFileInfo::prepateMetadata() uses openvgdb's to get the system. This is the 2nd pass for finding the correct system. The 1st pass is when GameFileInfo and its subclasses are originally constructed in LibraryWorker::findGameFiles(). During this 1st pass system lookup, we are checking our own systems database. The system name is not exactly the same as what is available in the openvgdb.

**Comment by athairus** [comment]
Is this bug moot once #206 is done?

**Comment by athairus** [comment]
Yes it is.
