### ISSUE TITLE
Version info

### ISSUE THREAD

**Issue by athairus** [team-phoenix/Phoenix#200]
**Format finalized below, see my last comment**

Phoenix will follow Semantic Versioning's version numbers in this format:
`major.minor.patch`

Increment major and reset minor and patch to 0 if:
- Phoenix is finally stable and feature-complete (version `1.0.0`)
- `1.x.x` and beyond: The user library schema changes and the user library must be updated (set up a means of doing this)

Increment minor and reset patch to 0 if:
- A major feature is introduced
- `0.x.x`: The user library schema changes and the user library must be updated (set up a means of doing this)

Increment the patch version for every release we put out that adds a minor feature or fixes bugs

We also need to define a standard way to update version numbers. The following locations should hold the version numbers:

```
frontend/phoenix.rc: string (ex. "0.0.1") and 4-tuple 32-bit integer (ex. 0, 0, 1, 0)
frontend/cpp/main.cpp: string
```

...and they should all be read from this file:
```
frontend/VERSION
```

with this format:
```
(string)
(4-tuple)
```

How will we get the contents of VERSION into the files that depend on it?

**Comment by athairus** [comment]
Also, happy 200th issue!

**Comment by RonnChyran** [comment]
Just use semver.org instead of deriving your own similar-but-not-quite
specification.

**Comment by athairus** [comment]
The only analogy to "Public API" I can see here is our database schema. Seems reasonable though.

**Comment by RonnChyran** [comment]
'Public API' is anything that interacts with the app. If you change database schema, bump major. If libretro updates their API and you update to comply, bump major. If you decide to update Qt to a theoretical Qt6 and your QML layouts need changes, bump major. 

Say you're adding LZMA format support without changing anything else. Since this is backwards compatible, bump minor. Maybe there's a small bug that prevents Dualshock 3 controllers from working. Since this is simply a bugfix, you would bump patch.

You can attach build metadata as per section 10

>Build metadata MAY be denoted by appending a plus sign and a series of dot separated identifiers immediately following the patch or pre-release version. Identifiers MUST comprise only ASCII alphanumerics and hyphen [0-9A-Za-z-]. Identifiers MUST NOT be empty. Build metadata SHOULD be ignored when determining version precedence. Thus two versions that differ only in the build metadata, have the same precedence. Examples: 1.0.0-alpha+001, 1.0.0+20130313144700, 1.0.0-beta+exp.sha.5114f85.

Essentially you append it to the version string with a + symbol.

**Comment by athairus** [comment]
Tag versions with the milestones we have, up to RC.

Maybe tag with a short revision hash, too?

`Phoenix 0.0.1-pre-alpha-9ca03f3`

**Comment by Limero** [comment]
printf "%s-%s" "$(cat frontend/VERSION)" "$(git rev-parse --short HEAD)"
Could be used to get something like "Phoenix 0.0.1-pre-alpha-9ca03f3" from an unofficial build. (If the frontend/VERSION file exists with "Phoenix 0.0.1-pre-alpha" inside)

**Comment by athairus** [comment]
TODO:
- Define a qmake config variable like `OFFICIAL`
- Add `frontend/BUILD-VERSION` to .gitignore
- If `OFFICIAL` defined, copy `frontend/VERSION` to `frontend/BUILD-VERSION`
- If `OFFICIAL` not defined, copy as above append shortened revision hash to this file
- Use `frontend/BUILD-VERSION` internally:
  - Copy to a `frontend/BUILD-VERSION.h` file:
```
#define PHOENIX_VER_STR "(contents of frontend/BUILD-VERSION)"
```

**Comment by athairus** [comment]
`git describe` gives me the info I need.

**Comment by athairus** [comment]
Integrating the value of git describe into a string and a windres version tuple was easy enough... it should work even after we stop appending `-milestone` to the tag, hopefully.
There was a whole lot of drama trying to get the version string into the .rc file and have it compile. Turned out there needed to be two levels of expansion to get the macro properly expanded into the .rc file. More info: http://stackoverflow.com/questions/2410976/how-to-define-a-string-in-gcc-command-line

I also had to do the same thing for `main.cpp`, so `windres` is nothing special.

`OFFICIAL` is not necessary at all, `git describe` does exactly what I want out-of-the-box.

The .h file wasn't needed, just add the two derivatives of `git describe` as `DEFINES` in `frontend.pro`, done.

**Comment by RonnChyran** [comment]
Semver uses the + operator to append build information. The - operator
indicates release channel, so Phoenix 0.0.1-pre-alpha-9ca03f3 means that
the release is a 'pre-alpha 9ca03f3' release than a 'pre-alpha' release
build 9ca03f3. What would be preferable is 'Phoenix
0.0.1-pre-alpha+9ca03f3'. This is important if you ever decide to parse
your semver versions.

**Comment by athairus** [comment]
Change has been integrated.

**Comment by athairus** [comment]
@RonnChyran I don't think that I'm going to ever parse the version string. Like I had mentioned before, Phoenix is no library or API. It's all just for developer/user convenience. The stuff appended after pre-alpha is generated by `git` automatically, I don't really want to put the work in to change that...

**Comment by athairus** [comment]
This is fully integrated now.
