### ISSUE TITLE
Add build instructions

### ISSUE THREAD

**Issue by hhirsch** [team-phoenix/Phoenix#230]
Hello,

can you please add build instructions to the readme?

**Comment by athairus** [comment]
The build instructions are available on the [wiki](https://github.com/team-phoenix/Phoenix/wiki). This wiki is linked to in the readme already. It changes often enough (and it's long enough) that it should belong there.

**Comment by hhirsch** [comment]
Only found the link after I read your comment here and looked at the source of the readme to find it. Imho a lot more people will build the game if it said:

# Build Instructions
And then a short text about the wiki and that it is easy to build.

Or something similar.
