### ISSUE TITLE
Build instructions not working

### ISSUE THREAD

**Issue by IamCarbonMan** [team-phoenix/Phoenix#239]
I really don't know a lot about building software or programming, but the [instructions](https://github.com/team-phoenix/Phoenix/wiki/Building) to build this fail at a weird point. I finish building with no apparent issues. But where is the executable? It says to use `cd debug && ./phoenix` but there is no such debug folder anywhere. What am I supposed to do?

**Comment by IamCarbonMan** [comment]
So, this should just be updated in the wiki. It should indicate that the compiled program is under phoenix-build/frontend/Phoenix (for linux).

**Comment by athairus** [comment]
Hi. I forgot to update the wiki to reflect a change we made earlier that made Windows not use separate `debug` and `release` folders like OS X and Linux don't. I also wrote that step which was clearly Windows-centric to begin with. Oops!

**Comment by IamCarbonMan** [comment]
Well I'm on Linux, so the issue I raised is not Windows-specific.
