### ISSUE TITLE
Windows, OS X deployment

### ISSUE THREAD

**Issue by Druage** [team-phoenix/Phoenix#260]
Deployment of Phoenix should be completed on Windows, OSX, and Linux, in order to produce binaries in a quick and timely manner.

=============

athairus:
Our first release will be a portable release.

- [x] Windows
  - Build with mingw on some Linux distro
    - Use MXE on Linux: http://mxe.cc/
  - Build script finalized

- [x] OS X
  - Built a static version of Qt 5.6.0 and changed Homebrew script for SDL2 2.0.4 to support 10.7+
  - Used `install_name_tool -L` to fix absolute .dylib locations to be relative to the executable
  - Bundled `libSDL2-2.0.0.dylib` and `libsamplerate.0.dylib` right next to the executable
  - Working on 10.7, 10.8, 10.11
    - 10.7 and 10.8 crash after a few moments with a QSG-related `EXC_BAD_INSTRUCTION` due to what seems to be an OpenGL driver bug (outside our control)
      - Confirmed on Parallels and possibly VMWare (don't remember)
  - Approx. 400+ warnings 
    - Ex. `:-1: warning: direct access in int qRegisterNormalizedMetaType<QList<QSslError> >(QByteArray const&, QList<QSslError>*, QtPrivate::MetaTypeDefinedHelper<QList<QSslError>, (QMetaTypeId2<QList<QSslError> >::Defined) && (!(QMetaTypeId2<QList<QSslError> >::IsBuiltIn))>::DefinedType) to global weak symbol QMetaTypeId<QList<QSslError> >::qt_metatype_id()::metatype_id means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.`
  - Create build script

- [x] Linux
  - Static Qt, mostly static build done
  - On a fresh install of Ubuntu 16.04 you'll need `libgstreamer0.10-0 libsamplerate0 libsdl2-2.0-0`

**Comment by athairus** [comment]
- [ ] Windows
  - Build with mingw on some Linux distro
  - Use static Qt 5
  - Use static standard library: `-static-libstdc++ -static-libgcc`
  - Include SDL2 and libsamplerate dlls

- [ ] OS X
  - TODO

- [ ] Linux
  - Pre-alpha will be distributed as a portable release: include all necessary libraries and rely on system libraries as little as possible
