### ISSUE TITLE
Auto-compress logs

### ISSUE THREAD

**Issue by athairus** [team-phoenix/Phoenix#294]
I could see the log folder becoming fairly large after a long time. We don't really print anything per-frame that would *really* make it grow quickly though.

Since we already have quazip, let's just use that.

**Comment by Druage** [comment]
Since the log files are already in a "Logs" folder, is it necessary to put them in a zip file, which is just another folder?

**Comment by athairus** [comment]
They need to be compressed individually, plain-text logs take up a lot of space and are very easily compressible.

**Comment by Druage** [comment]
oh i see now. I can do this.

**Comment by Druage** [comment]
Solved.
