### ISSUE TITLE
Double 360 Controllers as Player 1

### ISSUE THREAD

**Issue by Catarax** [team-phoenix/Phoenix#296]
When playing Sonic 3 on megadrive with 2 Xbox 360 controllers, the second controller is considered as player 1 too.

It should probably affect others consoles.

**Comment by Druage** [comment]
Just waiting to see if I can duplicate this issue.

**Comment by athairus** [comment]
This is because *all* controllers are currently hard-wired to player 1. Player assignment has not been implemented yet and will be in a future release.

**Comment by athairus** [comment]
Discussion continues in #300.
