### ISSUE TITLE
[Windows] The scraper doesn't work with NES nor N64 ROM's

### ISSUE THREAD

**Issue by pacoesni** [team-phoenix/Phoenix#309]
The scrapper function doesnt work with NES ROMS nor N64 ROMS. It works with Genesis, SNES and so on.

**Comment by athairus** [comment]
Hi, the database and scraper we currently use are temporary. A game must match exactly via CRC32, by its filename or have an extension that maps to a single console to be added to the library. Only the first two will give you artwork, and only if the database actually *has* artwork for that game. If you're really curious, grab an SQLite viewer and see the database for itself. It's at `frontend/metadata/openvgdb.sqlite`.

This will all be improved in the future.

**Comment by pacoesni** [comment]
I checked and match...probably a minor bug. But as you said, this can be improved. Your work is amazing, so keep doing it! This the only Front-end for libretro which really has a nice looking as OpenEmu.
