### ISSUE TITLE
User Interface

### ISSUE THREAD

**Issue by GreyAsteroid** [team-phoenix/Phoenix#311]
About 2 years ago there was a bunch of hype in the elementary OS community about this project after the founder posted about wanting a OpenEmu like experience for Linux and finding Phoenix. Ever since then I've been following this project somewhat loosely. 
One of the developers of the project had stated that Phoenix was somewhat following the elementary OS style guidelines http://imgur.com/a/sDGKN , is that still the case?
I see that the screenshot on the website and Github page have been changed to a sort of empty UI, is that some sort of wireframe mockup without some UI elements or is that what it looks like now?

**Comment by athairus** [comment]
The album you posted is mostly a mockup and was partially implemented a long time ago. We've moved on to a more flat interface. In the future we'll add the ability to theme Phoenix to your liking. Until then, we're using a flat theme because it's contemporary and easy to change.
