### ISSUE TITLE
Key binding customization?

### ISSUE THREAD

**Issue by ylluminate** [team-phoenix/Phoenix#312]
Where does one customize the keybindings for various game systems?  For example, I'd like to set up state save to be easy to trigger.  It appears that, at the moment, one cannot save states during game play in Phoenix.  (Also, I'd like to be able to, at some point, set Phoenix to have the OpenEMU behavior of saving state on exiting a game and restarting at that point as per a config option.)

**Comment by athairus** [comment]
It's not implemented yet. Check the release notes. It'll be added in a future version.

**Comment by athairus** [comment]
Release notes: https://github.com/team-phoenix/Phoenix/wiki/Phoenix-v0.0.1-(pre-alpha)-Release-Notes
