### ISSUE TITLE
Discord invite in README.md has expired

### ISSUE THREAD

**Issue by owcz** [team-phoenix/Phoenix#315]
Link resolves to: "The instant invite is invalid or has expired."

To change the expiration date: https://support.discordapp.com/hc/en-us/articles/208866998-Instant-Invite-101

**Comment by athairus** [comment]
Fixed.

**Comment by owcz** [comment]
Still getting the same error

**Comment by athairus** [comment]
The link was changed in the commit. Have you refreshed the page?

**Comment by owcz** [comment]
Yep https://discord.gg/umkBQ6a (the new one) leads to the same error

**Comment by athairus** [comment]
I'm not sure what to tell you. I've tried the link in incognito mode and was able to join just fine. Maybe you should try force-refreshing the page, clearing Discord's cookies or restarting the Discord app?
