### ISSUE TITLE
Issues with Cmake build.  

### ISSUE THREAD

**Issue by Alex-Keyes** [team-phoenix/Phoenix#318]
After creating a build dir and running cmake in it, I get this error regarding QT:

-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.8") 
CMake Error at CMakeLists.txt:49 (find_package):
  By not providing "FindQt5.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Qt5", but
  CMake did not find one.

  Could not find a package configuration file provided by "Qt5" with any of
  the following names:

```
Qt5Config.cmake
qt5-config.cmake
```

  Add the installation prefix of "Qt5" to CMAKE_PREFIX_PATH or set "Qt5_DIR"
  to a directory containing one of the above files.  If "Qt5" provides a
  separate development package or SDK, be sure it has been installed.

-- Configuring incomplete, errors occurred!
See also "/home/alex/Phoenix/build/CMakeFiles/CMakeOutput.log".

Any idea how to solve?  I'd be glad to help rewrite the installation guide after some help with this.

**Comment by athairus** [comment]
It's possible that CMake is simply unaware of where Qt exists on your system. Have you installed it via your distro's package manager? They tend to be out of date, I strongly recommend using Qt's own official installer and installing it to somewhere like your home directory or `/opt`.

**Comment by Alex-Keyes** [comment]
I fixed this - it had to do with the fact I was missing a few important qt5 packages.  After poking around for a while I was able to install the right ones and get cmake working.
