### ISSUE TITLE
Qt Quick not installed

### ISSUE THREAD

**Issue by Alex-Keyes** [team-phoenix/Phoenix#342]
After installing Quazip I was able to get the app compiled using cmake and make.  However, when i run it, I receive this error:
```W 11:31:12:765 unknown():0: QQmlApplicationEngine failed to load component 
               [unknown:0 unknown()]
W 11:31:12:766 unknown():0: file:///home/alex/git/Phoenix/QML/Phoenix/Phoenix/Phoenix.qml:319 Type Frontend unavailable
file:///home/alex/git/Phoenix/QML/Phoenix/Phoenix/Frontend.qml:70 Type LibraryHeader unavailable
file:///home/alex/git/Phoenix/QML/Phoenix/Frontend/LibraryHeader.qml:155 Type WindowControls unavailable
file:///home/alex/git/Phoenix/QML/Phoenix/Frontend/WindowControls.qml:1 module "QtQuick" version 2.6 is not installed
 
               [unknown:0 unknown()]
```
Obviously I need to install QtQuick but I was suprised that it could compile missing a component that's critical to the operation of Phoenix.

**Comment by athairus** [comment]
What's your distro and what version of Qt are you building against?

**Comment by Alex-Keyes** [comment]
Ubuntu 16.04 and I'm building against qt 5.5.1   Is this version too old?

**Comment by Alex-Keyes** [comment]
I have version 5.9.1 installed in my PC, with QtQuick installed.  It's located in ``/usr/include/x86_64-linux-gnu/qt5`` but  for some reason qt seems to be still using qt5.5, and I'm not sure where that's installed.  I will keep looking around for it.

**Comment by Alex-Keyes** [comment]
I changed the qtquick requirement from 2.6 to 2.5 and recompiled.  Then I was able to run the executable without any problems!  I guess lowering the requirement allowed for the executable to load the frontend.
