### ISSUE TITLE
Right-click menu in an awkward place

### ISSUE THREAD

**Issue by athairus** [team-phoenix/Phoenix#46]
![1](https://cloud.githubusercontent.com/assets/1216337/6141220/78f70924-b170-11e4-9d0f-c5b4983aa076.PNG)
![2](https://cloud.githubusercontent.com/assets/1216337/6141221/78f8a176-b170-11e4-9c97-ab7e50c2c387.PNG)

It should either be right at the mouse cursor or it should be touching the right edge of the menu item, either way overlapping the entry to the right.

**Comment by Druage** [comment]
Fixed.
