### ISSUE TITLE
Keyboard navigation

### ISSUE THREAD

**Issue by athairus** [team-phoenix/Phoenix#58]
Give users yet another way to navigate the library

**Comment by Druage** [comment]
Added keyboard navigation for arrow keys, page up / down support still needs work.

**Comment by flubbacrud** [comment]
Ignore the above commit. It should be on 58

**Comment by athairus** [comment]
Qt Quick provides some handy components for keyboard navigation, not sure exactly how much of it we've been using.

Behavior should only happen when BoxartGridView, etc. is in focus.

**Comment by athairus** [comment]
All previous comments besides my last one are for the old codebase.

**Comment by athairus** [comment]
Mostly done. 
TODO:
- Make sure collections and settings views work okay
- Indicate that the search bar and slider (most importantly) are focused
- Make fullscreen/close highlightable
- Maybe get GameView working?
