### ISSUE TITLE
Cannot double-click on games after searching in grid view

### ISSUE THREAD

**Issue by athairus** [team-phoenix/Phoenix#60]
Console says: 

[W] qrc:/qml/GameGrid.qml:368: TypeError: Type error
[W] qrc:/qml/GameGrid.qml:351: TypeError: Cannot read property 'showMenu' of null
[W] qrc:/qml/GameGrid.qml:361: TypeError: Cannot read property 'systemName' of null

Each time I try to click on something, and it doesn't get highlighted.

**Comment by Druage** [comment]
I cannot reproduce this error on Windows. I will try on OSX soon.

**Comment by Druage** [comment]
This error happens sometimes after you import or delete items. For some reason, the model isn't left in a valid state, and cannot be read.
