### ISSUE TITLE
Scrollbar only goes a fraction of the way through library at the bottom

### ISSUE THREAD

**Issue by athairus** [team-phoenix/Phoenix#65]
Steps to reproduce:
1. Have a large library (500+)
2. Use scrollbar to go to bottom (grab handle, drag to bottom)
3. See that it only makes it partway (for me, it's in the Bs)

When it reaches the bottom, it "jumps" up somewhat to accommodate what it thinks the rest of the library is.

**Comment by Druage** [comment]
This is a bug with the qml ScrollView itself.

**Comment by athairus** [comment]
No longer relevant.
