### ISSUE TITLE
Treat archive files as folders

### ISSUE THREAD

**Issue by athairus** [team-phoenix/Phoenix#66]
As long as this can be done almost as quickly as folders, we should not have to require the user to take an archive of roms and extract them first to import them into Phoenix or run them. Store ROM paths like this:

/path/to/rom/archive.zip:System name/Game.zip:Game.ext

To make things faster, take advantage of the fact that we'll be looking into the large archives many many times and implement caching. This might not be available in any library, we might have to do it ourselves.

**Comment by Druage** [comment]
Caching as in extracting the archive file and copying to game file into another folder? This would take up space though. We can just launch them like normal games, in which we open up the zip file every time and we locate the game file and play it that way. It shouldn't be too slow.

**Comment by athairus** [comment]
I meant caching as in making the process of opening an archive just to list its contents as fast as possible for any archive format that isn't designed to be instant. Not sure if there is one designed that way, just thinking ahead.

**Comment by Druage** [comment]
i guess you could cache the actual structure of the zip file. I'm guessing the speed we gain from this won't be substantial though.

**Comment by athairus** [comment]
Duplicate of #40.
