### ISSUE TITLE
Hook up all settings.

### ISSUE THREAD

**Issue by Druage** [team-phoenix/Phoenix#7]
This refers to making each setting in the settings window work properly. This encompasses configuring controls, to changing the preferred core, to muting the audio, etc.

**Comment by athairus** [comment]
Anything that is either non-essential or broken needs to be replaced with placeholders describing what they'll do in the final release. Input fields, radio buttons, etc should be greyed out.

**Comment by Druage** [comment]
Working on it

**Comment by athairus** [comment]
This is for the older version with the older theme. Make a new issue for this if we really need to...
