### ISSUE TITLE
Make hostFPS = coreFPS

### ISSUE THREAD

**Issue by athairus** [team-phoenix/Phoenix#81]
We need to know the exact frequency of the monitor Phoenix's window appears in if we're going to use VSync as a timing source. Why? Because we need to know exactly how much to stretch the audio data provided by the core every time retro_run() is called to occupy one monitor frame period's worth of time. If you think about it, any other way will result in the audio buffer not-so-slowly filling or draining as the converted audio is too long or too short.

Alternatively, we can look into ways to set the display's refresh rate equal to the core's refresh rate. That way we _know_ what the monitor's refresh rate is. Added benefit, the emulated game will run at exactly the same speed as the original console, which is of great interest to speedrunners (run a game on an emulator and console for 6 hours, assuming the emulator drops no frames the two should be at the exact same state assuming a deterministic console and exact same input). I assume of course that coreFPS which is provided by the core is actually accurate.

**Comment by Druage** [comment]
We need to finish implementing a dynamic rate control. Most of the work was already done with the audio.cpp files but i'd like to just use retroarch's resampler and tie that into our project. Basically just turn retroarch's resampler, into a library that we can import.

**Comment by athairus** [comment]
Dynamic rate control is added. However, the audio still crackles. Must have something to do with the audio output...

**Comment by Druage** [comment]
Only thing I can think of is make sure all of the audio errors have debug statements and check to see if the audiooutput's buffer is empty before any new audio data is fed into it. This is just me thinking, but if the internal audio output is getting overflows, it may be causing the static sounds.

**Comment by athairus** [comment]
This is a lead to a way of getting a better value for the true refresh rate of the monitor (Windows reports it in terms of integers) that's better than RA's way of just measuring it as a rolling average: the EDID. Find the EDID used by the monitor Phoenix's window resides in and you'll be able to calculate the true refresh rate based on the monitor timing. I personally use a utility called Custom Resolution Utility by ToastyX to override my Dell u2410's EDID to give me *exactly* 60.000Hz, which I can confirm using RA and an HDMI capture device (they report around 60.002). 

Windows: http://ofekshilon.com/2011/11/13/reading-monitor-physical-dimensions-or-getting-the-edid-the-right-way/

**Comment by athairus** [comment]
To REALLY get emulation that matches the core's `AVInfo->timing.fps`, we need to use a different timer source than VSync, skip or duplicate frames every once in a while to account for the timing differences, or... create and apply a custom EDID with the timing we want! This last option, if it can be pulled off cross-platform, would be perfect, as the monitor timing would perfectly match the core timing.

**Comment by athairus** [comment]
There's no way we can get a better timing source than vsync. However, it seems that we're dependent on the compositor to issue the update calls to the window, which don't happen if it's obscured or minimized. So, we either need to get vsync timing without having to output anything or maybe some kind of hybrid between vsync timing and QTimer. We can also look into possibly extending QTimer's code with a timer that runs with a higher granularity.

**Comment by athairus** [comment]
Possible library for reading EDIDs on NVIDIA cards on Windows: https://developer.nvidia.com/nvapi

**Comment by athairus** [comment]
**Windows**

Working example to fetch EDID: http://ofekshilon.com/2014/06/19/reading-specific-monitor-dimensions/
Get HWND from Qt: 
http://lists.qt-project.org/pipermail/interest/2013-June/007650.html
http://stackoverflow.com/questions/14048565/get-hwnd-on-windows-with-qt5-from-wid
Get HMONITOR from HWND (starting point for the example above): https://msdn.microsoft.com/en-us/library/windows/desktop/dd145064%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396

**Comment by athairus** [comment]
ToastyX convinced me NOT to use EDID data, it isn't reliable and difficult to enumerate, apparently.

Currently testing a new angle: setting refresh rates ourselves. NVIDIA's NVAPI provides this functionality. Unfortunately, when I tested the exact function we needed, NvAPI_SetRefreshRateOverride(), I got a return value of NVAPI_NO_IMPLEMENTATION. Darn.

I'm on the latest stable driver as of this post (353.06), so I'm at a loss as to what's going on. Maybe this is a dead end? I don't really want to support this feature if there's a list of configurations Phoenix WON'T support.

**Comment by athairus** [comment]
https://www.opengl.org/registry/specs/NV/wgl_delay_before_swap.txt

**Comment by athairus** [comment]
If we want to leave vsync off for low input latency during gameplay but still want to use Qt Quick's pretty UI capabilities, we'd better pay attention to this:

http://doc.qt.io/qt-5/qtquick-visualcanvas-scenegraph.html

Note: The threaded and windows render loops rely on the OpenGL implementation for throttling by requesting a swap interval of 1. Some graphics drivers allow users to override this setting and turn it off, ignoring Qt's request. Without blocking in the swap buffers operation (or elsewhere), the render loop will run animations too fast and spin the CPU at 100%. If a system is known to be unable to provide vsync-based throttling, use the basic render loop instead by setting QSG_RENDER_LOOP=basic in the environment.

**Comment by athairus** [comment]
A few pages on high res timers and Qt: 

http://www.folding-hyperspace.com/real-time-programming-tips/soft-real-time-performance.html

http://stackoverflow.com/questions/15730765/qt-high-resolution-timer

**Comment by athairus** [comment]
This guy on SO gave me some ideas to try:
http://stackoverflow.com/a/32717478/4190028

**Comment by athairus** [comment]
Continued in #220.
