### ISSUE TITLE
Network traffic being sent even when all artwork is fetched

### ISSUE THREAD

**Issue by athairus** [team-phoenix/Phoenix#82]
A small test library I've created has 28 games. The artwork was successfully scraped for each title. However, there is still a ton of traffic being generated by the Phoenix executable, even after restarting. Where is it coming from? What's it for?

**Comment by Druage** [comment]
The image cache send it angrier round of requests. :p it's not pretty but it works

**Comment by Druage** [comment]
I think I found a better way of doing this with qquickimageprovider. That way we cache the stored q image, instead of more requests.

**Comment by Druage** [comment]
Should be fixed with [this](https://github.com/team-phoenix/Phoenix/commit/cfaad832c09f793f35a55a423bece074d0f8723d) commit.
