### ISSUE TITLE
Cannot close settings pages on OS X

### ISSUE THREAD

**Issue by athairus** [team-phoenix/Phoenix#86]
Window controls do not appear, need either a 'close' button or clicking outside the window area closes it.

**Comment by Druage** [comment]
Ya  I noticed that also. It also has visual glitches with appearing.

**Comment by athairus** [comment]
Instead of fixing the window, a better fix is to follow OS X app conventions and just have a dedicated Preferences window that appears when Phoenix -> Preferences... is clicked instead of the settings dropdown. That means the gear has to go on OS X, too.

**Comment by athairus** [comment]
Irrelevant due to theme change.
