### ISSUE TITLE
Commenting and refactoring pass

### ISSUE THREAD

**Issue by athairus** [team-phoenix/Phoenix#93]
The entire project needs a nice pass of commenting and refactoring in order to make it easier for others to understand the code and contribute. The main thing the codebase needs is commenting.

**Comment by athairus** [comment]
All header files now have a brief description on how they fit in to the whole program.
The code itself should have a once-over just to explain sections that don't seem obvious at first glance.

As for the QML, MaqureeText is thoroughly documented. HeaderBar is partially documented, there were a few top-level things I couldn't figure out the meaning behind. All other QML has little to no comments in them, and may need some refactoring for readability.

In general, comment the stuff that doesn't seem obvious at first glance and comment the top-level stuff to make skimming with collapsed code easier. That goes for C++ and QML.

**Comment by Druage** [comment]
I know I know! You'll have some proper documentation by tonight
