### ISSUE TITLE
Errors importing games

### ISSUE THREAD

**Issue by mogorman** [team-phoenix/Phoenix#96]
when i try to add a folder this is the error I get
[W] [phoenix.library]: Unable to import game "gimmick.nes" ; error: QSqlError("", "Parameter count mismatch", "")
[W] [phoenix.library]: Unable to import game "contra.nes" ; error: QSqlError("", "Parameter count mismatch", "")
[W] [phoenix.library]: Error while trying to find metadata for imported games

**Comment by Druage** [comment]
Yeah this has been coming up a lot. Thanks for making it an issue! I'll work on fixing this next week

**Comment by mogorman** [comment]
Thanks.  if there is any information I can provide to help solve issue please let me know

**Comment by Druage** [comment]
I'm able to reproduce it on OSX, so I'll just debug it from there. What operating system were you using?

**Comment by mogorman** [comment]
im on debian jessie so gnu/linux build

**Comment by mogorman** [comment]
diff --git a/src/librarydbmanager.cpp b/src/librarydbmanager.cpp
index 30638bf..4a5854e 100644
--- a/src/librarydbmanager.cpp
+++ b/src/librarydbmanager.cpp
@@ -77,9 +77,9 @@ bool LibraryDbManager::createSchema() {
             QStringLiteral( "   /* file info */" ) %
             QStringLiteral( "   directory TEXT,\n" ) %
             QStringLiteral( "   filename TEXT UNIQUE,\n" ) %
-            QStringLiteral( "   sha1 BLOB\n" ) %
-            QStringLiteral( "   crc32 BLOB\n" ) %
-            QStringLiteral( "   rom_count BOOLEAN,\n" ) %
+            QStringLiteral( "   sha1 BLOB,\n" ) %
+            QStringLiteral( "   crc32 BLOB,\n" ) %
+            QStringLiteral( "   rom_count BOOLEAN\n" ) %
             QStringLiteral( ")" ) );
 
     q.exec( QStringLiteral( "CREATE INDEX title_index ON " ) % table_games % QStringLiteral( " (title)" ) );

**Comment by mogorman** [comment]
er i meant 96 not 98
